#!/usr/bin/env python

import sys, os

procs = {}
with open('Procfile') as f:
    for line in f:
        name, cmd = line.split(':', 1)
        procs[name.strip()] = cmd.strip()

env = dict(os.environ)
with open('.env') as f:
    for line in f:
        name, value = line.split('=', 1)
        env[name.strip()] = value.strip()

proc_name = sys.argv[1].strip()
proc_cmd = procs[proc_name]
shell_args = ['/bin/bash', '-c', proc_cmd]
os.execve(shell_args[0], shell_args, env)
